name: Get Latest Versions
on:
  push:
    branches:
      - master

jobs:
  getLatestVersions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: octokit/request-action@v2.x
        id: get_master_commit_tizen
        with:
          route: GET /repos/{owner}/{repo}/commits/master
          owner: jellyfin
          repo: jellyfin-tizen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Output master commit hash
        run: |
          echo "${{ fromJson(steps.get_master_commit_tizen.outputs.data).sha }}" > versions.txt
      - uses: octokit/request-action@v2.x
        id: get_latest_release_web
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: jellyfin
          repo: jellyfin-web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ fromJson(steps.get_latest_release_web.outputs.data).tag_name }}', '${{ fromJson(steps.get_latest_release_web.outputs.data).html_url }}'"
      - name: Commit Version Data
        run: |
          git config --global user.name 'jeppevinkel'
          git config --global user.email 'jeppevinkel@users.noreply.github.com'
          git add -A
          git commit -m "Automated Version Update"
          git push
